### ISSUE TITLE
Insufficient Permissions on S3 Bucket in Source Stage

### ISSUE THREAD

**Issue by SkxNMDI5** [awslabs/aws-refarch-cross-account-pipeline#1]
Hi,
nice article and sources.

I used the single click script and followed the indicated instructions.
But the "App" action in the "Source" stage is in error :
```
Insufficient permissions
The service role or action role doesn’t have the permissions required to access the Amazon S3 bucket named pre-reqs-artifactbucket-xxxxxxxxx. 
Update the IAM role permissions, and then try again.
Error: Amazon S3:AccessDenied:Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID:...
```

I can't see precisely which service role or action role as my account is restricted on CloudTrail access.

The bucket policy in the tools account seems to be ok with the real account numbers (but here in github with : dev = _123456789012_, tools : _234567890123_)
```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::123456789012:role/ToolsAcctCodePipelineCodeCommitRole",
                    "arn:aws:iam::234567890123:role/sample-lambda-CodeBuildRole"
                ]
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::pre-reqs-artifactbucket-xxxxxxxxxxxx",
                "arn:aws:s3:::pre-reqs-artifactbucket-xxxxxxxxxxxx/*"
            ]
        }
    ]
}
```

And the role (trusted entity :  tools account _234567890123_) in the dev account looks ok too :
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "codecommit:BatchGetRepositories",
                "codecommit:Get*",
                "codecommit:GitPull",
                "codecommit:List*",
                "codecommit:CancelUploadArchive",
                "codecommit:UploadArchive",
                "s3:*"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "kms:*"
            ],
            "Resource": "arn:aws:kms:eu-west-1:234567890123:alias/codepipeline-crossaccounts",
            "Effect": "Allow"
        }
    ]
}
```

Any advice on the way to go ?

**Comment by SkxNMDI5** [comment]
OK
I found it ! I used to pass the ARN of the alias for the CMK instead of the ARN of the CMK.
That's why S3 complained.

**Comment by jeetugswm** [comment]
I got a below issue when I run my aws code pipeline.
 AccessDenied: Access Denied status code: 403, request id: D18C063FBD, host id: q8QSdgeMXd9GzqiHAn9aR7e+Qh5TNjYfRjbXxQP73FZbZWjFj78IXQ= for primary source and source version arn:aws:s3:::pre-reqartifactbucket-1btcbp1ce/Infra-Prov/SourceOutp/EEB5s

I have give full s3 access but still access issue & tried alot.
Please let me know the solution to avoid this.

**Comment by aslangencer** [comment]
I had the same issue and in my case the KMS key that was to be used for this did not have the permissions to use the key. Once the role added to the key policy on the KMS console, it worked fine.

The S3 permission error was misleading.

**Comment by GMKBabu** [comment]
Hi
I'm getting this error please help me

Action execution failed
Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 24EE6735C01CFEBA; S3 Extended Request ID: a2/WMSUWqJFaeN3ZXkMD9hc6pshB3eCyXJya48286QACzZOkE8q63tf6olAu/gJ+jv/tReGZyps=)

**Comment by sureshbhusare** [comment]
I was getting similar issue. But then I found out I was using my KMS -key and which is not assigned to the bucket which I was using for codepipeline. 
So either use default AWS key or use KMS -key in bucket and check the policy for s3 access.

**Comment by SpicySyntax** [comment]
@aslangencer could provide sample json of what that policy looks like with the added roles? I am having a similar issue

**Comment by aslangencer** [comment]
This is a sample key policy that I used for cross-account deployment pipeline. 
It gives permission to use the key to other roles within the account where the key resides as well as other roles in other accounts.:
```
{
    "Version": "2012-10-17",
    "Id": "KMS Policy",
    "Statement": [
        {
            "Sid": "Allows admin of the key",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::111111111111:root"
            },
            "Action": [
                "kms:Create*",
                "kms:Describe*",
                "kms:Enable*",
                "kms:List*",
                "kms:Put*",
                "kms:Update*",
                "kms:Revoke*",
                "kms:Disable*",
                "kms:Get*",
                "kms:Delete*",
                "kms:ScheduleKeyDeletion",
                "kms:CancelKeyDeletion"
            ],
            "Resource": "*"
        },
        {
            "Sid": "Allow others use the key",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::111111111111:role/ToolsAcctCodePipelineCloudFormationRole",
                    "arn:aws:iam::111111111111:role/cloudformationdeployer-role",
                    "arn:aws:iam::111111111112:role/ToolsAcctCodePipelineCloudFormationRole",
                    "arn:aws:iam::111111111112:role/cloudformationdeployer-role",
                    "arn:aws:iam::111111111112:root"
                ]
            },
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:DescribeKey"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by abhi-accubits** [comment]
had the same issue
solution->  
1. use aws_kms_key instead of aws_kms_alias  
2. comment deletion_window_in_days, bypass_policy_lockout_safety_check = true and add a policy for s3 access.
yes, its insecure. for the time I'm just having an MVP. you can do it better. thx

I am at https://abhinand.in

**Comment by hubekpeter** [comment]
You are missing the **GetBucketVersioning** action in your policy, so the correct example looks like below. I don't know why it's not mentioned anywhere in the reference/documentation. And don't forget to enable the bucket versioning as well, it's required.:

```
- PolicyName: AccessRequiredByPipeline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                Effect: Allow
                Resource: !Sub ${YouBucket.Arn}/* 
              - Action:
                  - s3:GetBucketVersioning
                Resource: !Sub ${YouBucket.Arn}
                Effect: Allow
              - Action:
                  - kms:GenerateDataKey
                  - kms:Decrypt
                Effect: Allow
                Resource: !GetAtt KMSKey.Arn
```
