### ISSUE TITLE
What makes the Pipeline point to another account?

### ISSUE THREAD

**Issue by deleugpn** [awslabs/aws-refarch-cross-account-pipeline#10]
I've been using CodePipeline for nearly 2 years now and I never created any cross-account CodePipeline. The thing I want to understand is exactly what makes the pipeline on the Tools Account run the CloudFormation template on the Dev or Production account.
Looking through the template, the only thing I could think of was the `RoleARN`.
Is it the fact that the Role belongs to another account, therefore the cloudformation creation happens in the same account as the role?
Does this mean I can deploy to production account in multiple regions by simply changing the role ARN to point to a different region?

If the question is confusing, here's the final attempt to clarify my question: looking at the following block of code (https://github.com/awslabs/aws-refarch-cross-account-pipeline/blob/master/ToolsAcct/code-pipeline.yaml#L251-L304), what makes the resource be deployed in a different account than the one running the pipeline itself?

**Comment by heitorlessa** [comment]
Yes - That’s it. CloudFormation will assume that Role before
launching/updating a stack, and therefore using the creds to deploy in the
target account

**Comment by deleugpn** [comment]
This is huge. HUGE. I finally know how to reduce 120 pipelines to just 30.

**Comment by Senneseph** [comment]
Yeah, this was a confusing journey for me.  If they had just said "You can use CodePipeline to perform cross-account actions by first setting up the necessary IAM AssumeRole permissions and then assigning a Role from the target account to the CodePipeline's Action's RoleARN. " at the beginning, it would have helped a lot.
